// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybtwcsrqofyfoskwlmug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidHdjc3Jxb2Z5Zm9za3dsbXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzcyMzQsImV4cCI6MjA2NTg1MzIzNH0.5YUQ9JqQy08Nq5k8LjujK6uZ13VYNPcK8kp1pLvAHgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);